#!/usr/bin/env python

# Script to move files in filelist to folder excluded.
# filelist is generated by check_astrom
# To use , pass script name, and file containing list of flagged file names

import os,sys
import numpy as np
import pdb 
import glob

path = os.getcwd()
flagged_files = sys.argv[1]

filelist = np.loadtxt(flagged_files,dtype=str)

for filename in filelist:	
    os.system('mv '+ filename +' excluded/')

